server:
  port: 9001

spring:
  profiles:
    active: dev
  application:
    name: yh-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
